In [2]:
import pandas as pd

# Load the Excel file
file_path = '/Users/sohrabtellaie/Documents/GitHub/PrinciplesOfDataScienceCity/week07/london-borough-profilesV2.xlsx'
londonBorough = pd.read_excel(file_path)

# Force all columns to numeric, replacing non-numeric values with NaN
londonBorough_feat = londonBorough.apply(pd.to_numeric, errors='coerce')

# Drop columns where all values are NaN
londonBorough_feat = londonBorough_feat.dropna(axis=1, how='all')

# Display the cleaned data
londonBorough_feat.head()

,GLA Population Estimate 2013,GLA Household Estimate 2013,Inland Area (Hectares),Population density (per hectare) 2013,"Average Age, 2013","Proportion of population aged 0-15, 2013","Proportion of population of working-age, 2013","Proportion of population aged 65 and over, 2013",% of resident population born abroad (2013),% of largest migrant population (2013),...,"Female life expectancy, (2010-12)",Teenage conception rate (2012),Life satisfaction score 2012-13 (out of 10),Worthwhileness score 2012-13 (out of 10),Happiness score 2012-13 (out of 10),Anxiety score 2012-13 (out of 10),Proportion of seats won by Conservatives in 2014 election,Proportion of seats won by Labour in 2014 election,Proportion of seats won by Lib Dems in 2014 election,Turnout at 2014 local elections
0,8000,4514.371383,290.4,27.525868,41.303887,7.948036,77.541617,14.510348,NaN,NaN,...,NaN,NaN,8.10,8.23,7.44,NaN,NaN,NaN,NaN,NaN
1,195600,73261.408580,3610.8,54.160527,33.228935,26.072939,63.835021,10.092040,35.789474,5.814975,...,82.0,35.4,7.06,7.57,6.97,3.30,0.000000,100.000000,0.000000,38.16
2,370000,141385.794900,8674.8,42.651374,36.896246,20.886408,65.505593,13.607999,35.854342,2.234626,...,84.5,14.7,7.35,7.79,7.27,2.63,50.793651,42.857143,1.587302,41.10
3,236500,94701.226400,6058.1,39.044243,38.883039,20.282830,63.146450,16.570720,16.450216,2.169910,...,84.4,25.8,7.47,7.75,7.21,3.22,71.428571,23.809524,0.000000,NaN
4,320200,114318.553900,4323.3,74.063670,35.262694,20.462585,68.714872,10.822543,53.307393,10.717273,...,84.5,19.6,7.23,7.32,7.09,3.33,9.523810,88.888889,1.587302,33.00